{{- if .Values.mail -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "cost-optimization-operator.fullname" . }}-secret
  labels:
    {{- include "cost-optimization-operator.labels" . | nindent 4 }}
data:
  smtpserver: {{ .Values.mail.host | b64enc | quote }}
  smtpport: {{ .Values.mail.port | b64enc | quote }}
  smtpusername: {{ .Values.mail.username | b64enc | quote }}
  smtppassword: {{ .Values.mail.password | b64enc | quote }}

  {{- end }}