{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cost-optimization-operator.serviceAccountName" . }}
  labels:
    {{- include "cost-optimization-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cost-optimization-operator.serviceAccountName" . }}-role
  labels:
    {{- include "cost-optimization-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [ 'metrics.k8s.io','' ]
    resources: [ 'pods' ]
    verbs: [ "get" ]
  - apiGroups: [ '' ]
    resources: [ 'events' ]
    verbs: [ "delete","get","list","patch","create","update","watch" ]
  - apiGroups: [ 'apiregistration.k8s.io' ]
    resources: [ 'apiservices' ]
    verbs: [ "get" ]
  - apiGroups: [ 'org.jothika.costoperator' ]
    resources: [ 'costoptimizationrules', 'costoptimizationrules/status' ]
    verbs: [ "delete","deletecollection","get","list","patch","create","update","watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cost-optimization-operator.serviceAccountName" . }}-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-optimization-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cost-optimization-operator.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "cost-optimization-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

{{- end }}


